name: animations
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  line_awesome_icons: 1.0.4+2
  line_awesome_flutter: 1.0.1
  simple_animations: 2.2.2
  sa_v1_migration: 1.1.2
  supercharged: 1.10.0


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Play
      fonts:
        - asset: lib/assets/fonts/Play-Bold.ttf
        - asset: lib/assets/fonts/Play-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #

  # fonts:
  #    - asset: fonts/Play-Bold.ttf
  #    - asset: fonts/Play-Regular.ttf
  #         weight: 700
  #
